## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.2
  - 1.3
  - nightly
notifications:
  email: false
git:
  depth: false

jobs:
  allow_failures:
    - julia: nightly

# run tests
script:
  - julia --color=yes --project=@. -e 'using Pkg; Pkg.instantiate();'
  - julia --color=yes --project=@. -e 'using Pkg; Pkg.test()'
  #- julia --color=yes --project=@. examples/identification.jl  so far missing training data
  - julia --color=yes --project=@. examples/recipes.jl
  - julia --color=yes --project=@. examples/schema_visualization.jl

after_success:
  # push coverage results to Coveralls
  - julia --color=yes -e 'cd(Pkg.dir("JsonGrinder")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia --color=yes -e 'cd(Pkg.dir("JsonGrinder")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
